### PR TITLE
Created basic scaffolding for signing api (bug 1210021)

### PR DESCRIPTION
**Pull request by Nolski**

### CODE REVIEW

**Comment by andymckay** [comment]
Any reason for being in a folder called signing_api? The key view is for a viewing the API key? That feels like it is a generic api auth method and not a signing_api one. I think @mstriemer has a plan for the API end points for getting add-on status.

**Comment by mstriemer** [comment]
I'd argue that the `_api` portion shouldn't be in the app name. I'm not sure if it should be `signing` or `submission` but probably not critical to get caught on that right now.

I filed [bug 1208561](https://bugzilla.mozilla.org/show_bug.cgi?id=1208561) and [bug 1208572](https://bugzilla.mozilla.org/show_bug.cgi?id=1208572) for the two endpoints I think we need and this looks consistent with that (although I'm not sure what the key views are for).

**Comment by Nolski** [comment]
@mstriemer I agree on the `_api` naming. I'll change that. As far as the key endpoints go, those are for managing the user's API keys ([1209224](https://bugzilla.mozilla.org/show_bug.cgi?id=1209224) and [1209222](https://bugzilla.mozilla.org/show_bug.cgi?id=1209222)).

@andymckay I left the API key methods in the signing app since I was not yet sure if the authentication of this API will be consistent across the whole site. If we use Hawk tokens for this API do we plan on doing that site wide? How will this affect the website if most of our backend is API based? So i suppose it might be nice to have that functionality sit where it's being used for the time being.

**Comment by magopian** [comment]
Wondering if we should "link" this API to the one that already exists in `apps/api/` (which I have no idea if it's used, by who, what for, and we have the current version in piston, and there's been a rewrite in DRF that isn't used)

**Comment by andymckay** [comment]
Lets find out where `/apps/api/` is used. Here you go @magopian https://bugzilla.mozilla.org/show_bug.cgi?id=1210423

**Comment by kumar303** [comment]
Nolski said he wanted to close this since the implementations for this stuff are already in progress. If we need to reorganize the code once we start integrating patches from different people we can come back and do that.

**Pull request closed without merging**
