### PR TITLE
Bug 1197139 - Add version history link to the Development Channel section

### PR DESCRIPTION
**Pull request by palant**
This turned out simpler than I thought, unless I am missing something.

### CODE REVIEW

**Comment by magopian** [comment]
This looks perfect ;)

Can you please add a test for that? Just making sure that the link is displayed (if there are beta versions), and that it's the correct one.

**Comment by palant** [comment]
I actually looked around already to see whether there is a test for the existing version history link - I didn't find any. But I'll check again to see where this test would make sense.

**Comment by magopian** [comment]
How about here: https://github.com/palant/olympia/blob/c803bd575873564052ed81220d4939b28710b671/apps/addons/tests/test_views.py#L580 ?

**Comment by palant** [comment]
Sure, will do though probably not today.

**Comment by magopian** [comment]
no rush! Let me know if I can help

**Comment by palant** [comment]
The latest commit now adds tests for both version history links.

**Comment by magopian** [comment]
Excellent, thanks!
r+

**Comment by magopian** [comment]
Fixed in 021deabfa8ad04445eb5fb398fab491d38248df6

**Pull request closed without merging**
