### PR TITLE
Fix selector engine blowing with invalid ids

### LINKED ISSUE #1608: JS error after Add-on icon click followed by page refresh
Steps to reproduce:
1. Load AMO-stage details page for any add-on (with JS tab opened in the web console)
2. Click Add-on icon
3. Refresh the page

Expected results:
There are no issues.

Actual results:
There is a JS error displayed in the console.

Notes/Issues:
Verified on FF44(Win 7). Issue is reproducing on AMO-stage, dev and prod.
Please see the screenshot:

### PR DESCRIPTION
**Pull request by muffinresearch**
Fixes #1608

### CODE REVIEW

**Comment by magopian** [comment]
This is a weird piece of code, do we have a better way around it? Maybe first check with `document.getElementById`?

r+wc

**Comment by muffinresearch** [comment]
> This is a weird piece of code, do we have a better way around it? Maybe first check with document.getElementById?

What's weird, my patch or the original code? 

The regex just checks what is acceptable as a valid id (in a quite liberal way since HTML5 allows everything that's not spaces [1]). We're not likely doing anything too crazy since the original code is just dealing with opening sections denoted by and id. 

The regex ignores things like `#id=foo` which is what is causing the original problem.

As far as the regex goes - It must start with '#', `\w` is analogous to `[A-Za-z0-9_]` and I'm adding `-` and `.` to that. Other than that the repetition is one or more.

I suppose the alternative could look like this:

```javascript
var fragment = window.location.hash;
if (fragment) {
    // If the page URL is pointing directly to an expando section (e.g.
    // external link to that section), make sure the contents are visible.
    // The getElementByID ensures the element exists and doesn't
    // allow us to pass invalid selectors to jQuery.
    var $target = $(document.getElementById(fragment.substr(1)));
    if ($target.hasClass('expando'))
        $target.addClass('expanded');
}
```

But then I'm not sure how direct that is? 

[1] https://mathiasbynens.be/notes/html5-id-class

**Comment by magopian** [comment]
I was talking about the original code, taking just any fragment, converting it into a jquery node, and then expanding it. Your code is very good ;)

Thinking again about it, and as you explained yourself, making it "sure that it's a proper existing id" doesn't really add anything to it, so let's just leave it as is, thanks!

**Comment by muffinresearch** [comment]
> Thinking again about it, and as you explained yourself, making it "sure that it's a proper existing id" doesn't really add anything to it, so let's just leave it as is, thanks! 

Ok! Btw I do like the simplicity of the `document.getElementById` idea - it's clever and works well in practice since the null when the id doesn't exist just means that jquery does nothing with it and when it returns an element jquery just wraps that with a jquery object.

The only thing there is it looks a bit odd, passing `document.getElementById` as an arg to `$()`.

**Pull request merged**
