### PR TITLE
Remove 'emailhidden' flag (bug 1214848)

### PR DESCRIPTION
**Pull request by EnTeQuAk**
We're assuming and hiding email addresses everywhere by default now, thus removing the flag since most of our users hide their email address anyway.

This removes all occurrences in the code, the database flag will be dropped in a later iteration.

### CODE REVIEW

**Comment by magopian** [comment]
I think this PR is missing:
1/ the removal of the `emailhidden` field on the UserProfile
2/ a migration to remove it from the database (we use https://github.com/mozilla/schematic --which is a pain-- for migrations, they're all stored in the `migrations` folder)
3/ removal from all the fixtures

Nice thing this is going away, thanks for taking care of it!

**Comment by EnTeQuAk** [comment]
@magopian well, the database and fixture part would come next week, I talked to Andy and we wanted to do this in two steps since we're not yet sure how long dropping this table would take and wanted to remove if from the interface first and then worry about the migration part.

So there'll be a follow-up pr for this (and I'll create a follow-up bug too)

Also we have a small grace period for people to complain that they really really want to show their email addresses.

**Comment by magopian** [comment]
Makes sense!

Regarding "how long dropping this field on the table takes", I'm pretty sure deleting a col is really fast. Don't take my word for it though ;)

So that's a r+

**Comment by EnTeQuAk** [comment]
Merged in b4b07e2fa6a1324899eeed8e03df124b25507bda

**Pull request closed without merging**
