### PR TITLE
upgrade pillow to 2.7.0

### PR DESCRIPTION
**Pull request by magopian**
https://www.djangoproject.com/weblog/2015/jan/02/pillow-security-release/

### CODE REVIEW

**Comment by clouserw** [comment]
I restarted this on travis to see if it was intermittent

**Comment by magopian** [comment]
It's not, there must have been some API change that I'll have to investigate. It was worth a try ;)

**Comment by magopian** [comment]
I believe I have a fix now

**Comment by clouserw** [comment]
r+

**Pull request merged**
