### PR TITLE
Remove email checks (bug 1214844)

### PR DESCRIPTION
**Pull request by EnTeQuAk**
Remove email checks for Theme ownership transfer and in addon "Authors & License" screen.

### CODE REVIEW

**Comment by andymckay** [comment]
Is there a HTTP end point this functionality hits that needs removing too?

**Comment by EnTeQuAk** [comment]
There is and it's still being used in the "Contributors & More" section of the addon-edit screen. That's the screen that get's a bit refactoring in bug 1207807 so I thought that's not context of this PR.

**Comment by andymckay** [comment]
That's cool then, as long as eventually we remove the HTTP end point ;)

**Comment by EnTeQuAk** [comment]
Squashed and merged in 24d85149d3c6b201e67a75c411f4ba32b381f22c

**Pull request closed without merging**
