### PR TITLE
Hey Travis, get non-wheels from /olympia like prod

### PR DESCRIPTION
**Pull request by kumar303**

### CODE REVIEW

**Comment by magopian** [comment]
Makes sense I guess. But then, how do we make sure nothing is missing in /olympia if prod only takes from there?

**Comment by kumar303** [comment]
we should probably just copy all test deps into /olympia

**Comment by magopian** [comment]
and then configure travis not to get anything from the root? Makes sense.

**Comment by magopian** [comment]
r+

**Comment by kumar303** [comment]
I'll get this in to fix the build then try another with only `/olympia`.

**Pull request merged**
