### PR TITLE
Track addons and themes install (bug 1128713)

### PR DESCRIPTION
**Pull request by magopian**
Fixes [bug 1128713](https://bugzilla.mozilla.org/show_bug.cgi?id=1128713)

### CODE REVIEW

**Comment by mstriemer** [comment]
I don't see a `data-name` on the themes landing page https://addons.mozilla.org/en-US/firefox/themes/.

**Comment by magopian** [comment]
Oh wow, indeed, well spotted! I'll come up with something else, thanks!

**Comment by magopian** [comment]
It seems I had missed some code which was in charge of installing themes from the themes landing page, it's now fixed: https://github.com/mozilla/olympia/pull/639/files#diff-42e4dd1a15ebc447a40b27a6b94c7aa0R27

**Comment by mstriemer** [comment]
Can't verify as mentioned about but that looks good to me. r+

**Pull request merged**
