### PR TITLE
Bug99

### PR DESCRIPTION
**Pull request by pemmasanikrishna**

### CODE REVIEW

**Comment by magopian** [comment]
Still the same issue :/

Did you create your branch off master?

**Comment by pemmasanikrishna** [comment]
@magopian  yes i did and now all the test cases got passed.

**Comment by magopian** [comment]
Ah, I understand. If you need help setting up the repo locally, don't hesitate to come on irc, I'll be happy to give you a hand. In the meantime, I'll finish the PR for you.

Thanks!

**Comment by pemmasanikrishna** [comment]
@magopian  ya ,i dont have my system with me right now so i was using the web UI. But had the repo locally in my system :)

**Comment by magopian** [comment]
Closed in favor of #607

**Pull request closed without merging**
