### PR TITLE
Add some helpers to test error logging on celery

### PR DESCRIPTION
**Pull request by kumar303**

### CODE REVIEW

**Comment by andymckay** [comment]
r+

**Comment by magopian** [comment]
Will you have access to a shell on the server you want to test that on? Otherwise just create a new admin url which does the same thing, instead of the management command?

**Comment by kumar303** [comment]
> Will you have access to a shell on the server you want to test that on?

Yeah, jason does so he can run it. Hmm, I guess we could add an admin page too but it would require wiring up a few extra things.

**Comment by madalincm** [comment]
Please add STR here or mark it with qa- if no QA is needed.

**Pull request merged**
