### PR TITLE
Add a queue flag for WebExtension (issue #940)

### LINKED ISSUE #940: Add an icon in the queue for webextensions
The same way we have icons for restartless or jetpack add-ons.

See the "Flags" column below:
screen shot 2015-11-17 at 11 39 18

This will need https://bugzilla.mozilla.org/show_bug.cgi?id=1219772 first (which depends on #885)

### PR DESCRIPTION
**Pull request by magopian**
Fixes #940

Disclaimer: the icon is a placeholder, if you have a better one, let me know ;)

screen shot 2015-12-02 at 16 02 16

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
Don't we have an more official icon for web extensions? Besides that, I think you forgot another migration

**Comment by magopian** [comment]
I didn't find anything official for the icon, so I just created one as a placeholder. And this time, no migration needed, it's not a real model, it's a kind of db view ;)

**Comment by wagnerand** [comment]
Can the displayed type (second column) be WebExtension, so we can filter for it?

**Comment by EnTeQuAk** [comment]
after small discussion about the icon on IRC I'm r+ :smiley: :

**Pull request merged**
