### PR TITLE
Update sr-Latn using sr (Cyrillic) content converted with icu4c

### PR DESCRIPTION
**Pull request by flodolo**

### CODE REVIEW

**Comment by clouserw** [comment]
@flodolo I missed this and already re-extracted.  Can you re-run the conversion script on the new files?  Sorry for the trouble

**Comment by flodolo** [comment]
I keep having issue with this freaking file: ´´´apps/files/fixtures/files/jétpack.xpi´´´. It keeps going crazy every time I create a branch or update, can't even revert the file.

I wonder if I'm hitting some git bug on OS X (it's still 2.2.1).

**Comment by flodolo** [comment]
No clue if Travis is failing because of me

**Comment by magopian** [comment]
@flodolo yeah this file is made on purpose with some weird encoding to "cause issues" on some filesystems. It's made to be annoying for the tests ;)

In your case, you can just ignore it and don't commit it.

Regarding Travis, it's having issues lately with the requirements installation, not sure why. I've restarted it.

**Comment by flodolo** [comment]
The strange thing is that this file is pretty old, and always worked. It started only in the last weeks, so I assume it's git related :-\

**Comment by magopian** [comment]
yeah, I have the issue also from time to time... you should be able to just ignore it.

**Comment by magopian** [comment]
Travis build is now fixed

**Comment by clouserw** [comment]
thanks!

**Pull request merged**
