### PR TITLE
Bug 1172044: Part 2 - Allow editors to flag or unflag validator messa…

### PR DESCRIPTION
**Pull request by kmaglione**
…ges as ignorable.

### CODE REVIEW

**Comment by magopian** [comment]
I would have loved a birds eye view of what the changes are, and a few screenshots.

r+wc

**Comment by kmaglione** [comment]
I'll add screenshots.

**Comment by kmaglione** [comment]
This is the only visible change:

cc33797bf983f193

Checking or unchecking the checkbox sends an XHR, which stores an annotation for the `ignore_duplicates` flag of that message, in that file. Loading the validation results page again shows shows the new value of the flag in the checkbox.

Each time a new version is uploaded, the value of the store duplicates flag is copied to any message that still exists in that version, and so on in any succeeding new version upload.

**Comment by magopian** [comment]
r+

**Pull request merged**
