### PR TITLE
Add GA tracking & parent frame callback to static pages.

### PR DESCRIPTION
**Pull request by jpetto**
Bug 1127905.

Also Cleaned up indentation.

### CODE REVIEW

**Comment by chrismore** [comment]
@magopian @clouserw  r?

**Comment by clouserw** [comment]
if it does what you want it wfm.  Please test it on -dev before friday. thanks

**Comment by jpetto** [comment]
Confirmed behavior is working as expected on -dev. I'm getting messages posted to the parent frame and seeing GA events firing.

**Comment by chrismore** [comment]
Woo hoo!

**Pull request merged**
