### PR TITLE
Give a 503 when in read-only for signing (see #1050)

### PR DESCRIPTION
**Pull request by mstriemer**
This just gives a 503 on the upload version API since I think that's the only one we care about now and I wanted this to be small.

This is related to #1050.

### CODE REVIEW

**Comment by andymckay** [comment]
Can you add some docs to readthedocs to explain a 503 please?

r+wc

**Comment by mstriemer** [comment]
I guess add it to the general API docs? I'm guessing at some point we'll want a more general solution so it should go there.

**Comment by andymckay** [comment]
Yeah I'm thinking we should have a general API responses that says things like: 503..., 404..., 200... etc and then we only need to document unusual cases on each API.

**Comment by mstriemer** [comment]
screenshot 2015-12-04 16 50 41

**Pull request merged**
