### PR TITLE
move to new repo

### PR DESCRIPTION
**Pull request by andymckay**

### CODE REVIEW

**Comment by mstriemer** [comment]
Why is it `stage`?

**Comment by andymckay** [comment]
Because that's what @jasonthomas told me :)

**Comment by mstriemer** [comment]
We still want to reference the old one in the docs/README.rst?

**Comment by mstriemer** [comment]
And `requirements/docker.txt`?

**Comment by andymckay** [comment]
got those two in that commit ^

**Comment by mstriemer** [comment]
Cool. r+

**Pull request merged**
