### PR TITLE
Add the google analytics scripts to the discovery pages (bug 1191391)

### PR DESCRIPTION
**Pull request by magopian**
Fixes [bug 1191391](https://bugzilla.mozilla.org/show_bug.cgi?id=1191391)

This is also linked to [bug 1128713](https://bugzilla.mozilla.org/show_bug.cgi?id=1128713)

### CODE REVIEW

**Comment by mstriemer** [comment]
Looks like [`preload`](https://github.com/mozilla/olympia/blob/f5e0cb561eae56fd8506b4730ca68ed88d99c348/lib/settings_base.py#L663-L667) loads jQuery, preloaded.js and analytics.js. Do you want all three or just analytics.js?

If jQuery it already loaded it doesn't matter much as long as it isn't being duplicated but I'd imagine this is supposed to be a trimmed down AMO page that loads quickly so maybe it isn't needed.

r+wc

**Comment by magopian** [comment]
Very good point, very good question.

**Comment by magopian** [comment]
I've instead added the `analytics.js` script to the `zamboni/discovery` bundle. What do you think @mstriemer?

**Comment by mstriemer** [comment]
:+1:  r+

**Pull request merged**
