### PR TITLE
Fix duplicate entries on credits page

### PR DESCRIPTION
**Pull request by wagnerand**
This fixes a regression from #1295

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
Looks good to me, I'd prefer having a test for this though.

**Comment by wagnerand** [comment]
Considering https://github.com/mozilla/olympia/pull/1295#issuecomment-170171605, we could rather optimize the page and then have proper tests, but my time is too limited for that.

**Comment by EnTeQuAk** [comment]
Considering that I opened https://github.com/mozilla/olympia/issues/1430 and let's do r+ here for now.

**Comment by wagnerand** [comment]
Thanks. I think Andy appreciates that new issue!

**Pull request merged**
