### PR TITLE
Bugs 1181741, 1179697: Allow editors to download disabled files, allow staff to download arbitrary uploads.

### PR DESCRIPTION
**Pull request by kmaglione**

### CODE REVIEW

**Comment by magopian** [comment]
Should the new urls be accessible somewhere? Or are they only supposed to be "forged" for each particular file? Would it make sense to display this link maybe in the devhub or the editor tools for ease of access?

**Comment by magopian** [comment]
Regarding the fix for [bug 1181741](https://bugzilla.mozilla.org/show_bug.cgi?id=1181741), is it to make it easier to download a file given its uuid, instead of going through the database to get its addon/version, and then go to the appropriate devhub page, and download it from there?

**Comment by magopian** [comment]
If so, should we instead have a new url that displays the addon and version of a file given its uuid? Would that make sense and be also useful for other usecases?

**Comment by magopian** [comment]
Ah, sorry, it's `FileUpload`, not files themselves, scrap my previous two comments ;)

**Comment by magopian** [comment]
This is excellent work, thanks!

r+wc

**Comment by kmaglione** [comment]
I can't really think of anywhere it might make sense to add links, except maybe from standalone validation results. And it does seem like they might occasionally be useful there. But I mostly need them for dealing with errors that come up in Sentry, and there's nowhere that we currently expose those objects.

**Comment by magopian** [comment]
Fair. Should we document this somewhere? I'm afraid that this knowledge will get lost with time, maybe add it to mana? I've share a "AMO useful commands" mana page with you.

**Comment by kmaglione** [comment]
Agree, should definitely be documented. I'll also add something to the "Sentry to Bugzilla" add-on to create links in Sentry.

**Comment by kmaglione** [comment]
Merging despite failed tests, since they're unrelated to this PR and are also failing on master.

**Pull request merged**
