### PR TITLE
Restructure module/folder structure

### PR DESCRIPTION
**Pull request by EnTeQuAk**
This is a preview of the new folder/module structure, this is not yet ready to merge.

Todo:

* [x] Rebase to master
* [x] Update and fix all remaining imports
* [x] Update settings, urls includes, etc.
* [x] Fix mocks to use new module paths
* [x] Make sure test-suite runs
* [x] squash changes
* [x] Notify jason about all deployment-related changes
* [x] fix, update packages in pyrepo
* [ ] merge!

### CODE REVIEW

**Comment by diox** [comment]
Note: also notify @flodolo / @mathjazz before merging this (and other PR that may move locale files around) so that they can update the l10n dashboards.

**Comment by EnTeQuAk** [comment]
I just moved back the `locales` folder since `tower` expects it hard to be at `settings.ROOT` and I didn't want to mess with that config in this PR.

**Comment by diox** [comment]
r+, but as mentioned on IRC please squash the `locales/` folder back & forth move to avoid complications. Also, there is a conflict now, but it should be trivial.

**Comment by EnTeQuAk** [comment]
@diox squashed and rebased to master. tests are green too. It'd be nice to see some better diff of this branch to avoid re-adding some of the cleanups we have in master but what I see appears to be fine.

**Comment by EnTeQuAk** [comment]
@flodolo / @mathjazz mind taking a look at this? In the end I'm not moving the locales but at least in git-history they do, would something like that confuse the dashboards?

**Comment by flodolo** [comment]
I'm not completely sure how to check this (4k files, GitHub doesn't even show the list of changed files).

If I compare master with [your branch ](https://github.com/EnTeQuAk/olympia/tree/feature/restructure-modules/locale)I don't see any change for localization: .po files are still in `/locale` and maintained the same names. 

I can't think of any issue on my side, and since this will be merged in one step, I don't think Pontoon will bother either (but better wait for @mathjazz to confirm).

**Comment by mathjazz** [comment]
@EnTeQuAk If you didn't change locale files (names or paths), you're good to go.

**Comment by EnTeQuAk** [comment]
Great, thanks for the information!

**Comment by EnTeQuAk** [comment]
Ugh, failing because of missing packages in pyrepo, will fix this and hopefully gtm soon. This branch is becoming a huge burden to maintain.

**Comment by EnTeQuAk** [comment]
@jasonthomas Trying to keek you in the loop of this. I updated the file/folder structure of olympia and some paths have changed. The probably most important ones:

 * Olympia needs to be installed as a package now too `pip install path-to-olympia`
 * `sites/prod/` as moved to `src/olympia/conf/prod/` - same for `dev` and `stage`
 * The WSGI endpoint is now `olympia.wsgi` (`src/olympia/wsgi.py`), newrelic initialization moved to this file

I'm not sure if there's anything else important for deployment, let me know if there's something I can help with updating the puppet config for this.

**Comment by jasonthomas** [comment]
Thanks for the heads up. I can work on the puppet/deployment stuff early next week.

**Comment by jasonthomas** [comment]
I started working on this today, I have a few questions:

What is the best way to create a python package? I am using the following command:
```python setup.py sdist```.

I see ```version='0.1.0'``` in setup.py. Are we planning to update this with the tag value when we tag a release?

**Comment by EnTeQuAk** [comment]
Uhm, either like that or "pip install - e path-to-source" both will do
pretty much thethe same.

My idea would be to update the version with the tag, I guess that would
make sense since we already have that versioning scheme.


On Wed, Jan 27, 2016, at 05:41 PM, Jason Thomas wrote:
> I started working on this today, I have a few questions:


> What is the best way to create a python package? I am using the
> following command: python setup.py sdist.


> I see version='0.1.0' in setup.py. Are we planning to update this with
> the tag value when we tag a release?


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/mozilla/olympia/pull/1081#issuecomment-175735810

**Comment by EnTeQuAk** [comment]
@jasonthomas the way celery is started has changed too:

`celery -A olympia.amo.celery:app worker` - note the updated app-module path.

**Comment by kumar303** [comment]
Instead of `src/olympia/` could it just be `olympia/` ? I think that is pretty standard nowadays for Python packages. :bike: :door:

**Comment by EnTeQuAk** [comment]
I honestly don't have any preference for src/ vs directly olympia/ so I'll just do it that way :smiley:

**Comment by kumar303** [comment]
It's not really so important. I was mistaken at first that the import path would have to be `from src.olympia import ...`.

**Comment by EnTeQuAk** [comment]
Ah no, we're installing it directly as 'olympia'  and removing all
sys.path hacks and all requirements for altering the pythonpath.

On Wed, Feb 3, 2016, at 04:51 PM, Kumar McMillan wrote:
> It's not really so important. I was mistaken at first that the import
> path would have to be from src.olympia import ....


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/mozilla/olympia/pull/1081#issuecomment-179303435

**Pull request merged**
