### PR TITLE
specifies docker-compose version

### PR DESCRIPTION
**Pull request by mdaif**

### CODE REVIEW

**Comment by muffinresearch** [comment]
Hi. Thanks for the patch. Do you have a paste/gist of the actual problem you're seeing? I think we'd want to look to fix the actual root cause rather fix the version to an old version of the docker-compose lib.

**Comment by mdaif** [comment]
sure ... I created another virtualenv and re-installed the latest stable version of docker-compose .. here is the result ...

```
$ virtualenv env2
New python executable in env2/bin/python
Installing setuptools, pip...done.
$ source env2/bin/activate
(env2)$ pip install docker-compose
Downloading/unpacking docker-compose
  Downloading docker-compose-1.5.1.tar.gz (104kB): 104kB downloaded
  Running setup.py (path:/home/mdaif/workspace/mozilla/olympia/env2/build/docker-compose/setup.py) egg_info for package docker-compose
    
    warning: no previously-included files found matching 'README.md'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.un~' found anywhere in distribution
Downloading/unpacking docopt>=0.6.1,<0.7 (from docker-compose)
  Downloading docopt-0.6.2.tar.gz
  Running setup.py (path:/home/mdaif/workspace/mozilla/olympia/env2/build/docopt/setup.py) egg_info for package docopt
    
Downloading/unpacking PyYAML>=3.10,<4 (from docker-compose)
  Downloading PyYAML-3.11.tar.gz (248kB): 248kB downloaded
  Running setup.py (path:/home/mdaif/workspace/mozilla/olympia/env2/build/PyYAML/setup.py) egg_info for package PyYAML
    
Downloading/unpacking requests>=2.6.1,<2.8 (from docker-compose)
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB): 470kB downloaded
Downloading/unpacking texttable>=0.8.1,<0.9 (from docker-compose)
  Downloading texttable-0.8.4.tar.gz
  Running setup.py (path:/home/mdaif/workspace/mozilla/olympia/env2/build/texttable/setup.py) egg_info for package texttable
    
Downloading/unpacking websocket-client>=0.32.0,<1.0 (from docker-compose)
  Downloading websocket_client-0.34.0.tar.gz (193kB): 193kB downloaded
  Running setup.py (path:/home/mdaif/workspace/mozilla/olympia/env2/build/websocket-client/setup.py) egg_info for package websocket-client
    
Downloading/unpacking docker-py>=1.5.0,<2 (from docker-compose)
  Downloading docker-py-1.5.0.tar.gz (59kB): 59kB downloaded
  Running setup.py (path:/home/mdaif/workspace/mozilla/olympia/env2/build/docker-py/setup.py) egg_info for package docker-py
    
Downloading/unpacking dockerpty>=0.3.4,<0.4 (from docker-compose)
  Downloading dockerpty-0.3.4.tar.gz
  Running setup.py (path:/home/mdaif/workspace/mozilla/olympia/env2/build/dockerpty/setup.py) egg_info for package dockerpty
    
Downloading/unpacking six>=1.3.0,<2 (from docker-compose)
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking jsonschema>=2.5.1,<3 (from docker-compose)
  Downloading jsonschema-2.5.1-py2.py3-none-any.whl
Downloading/unpacking enum34>=1.0.4,<2 (from docker-compose)
  Downloading enum34-1.0.4.tar.gz
  Running setup.py (path:/home/mdaif/workspace/mozilla/olympia/env2/build/enum34/setup.py) egg_info for package enum34
    
Downloading/unpacking backports.ssl-match-hostname (from websocket-client>=0.32.0,<1.0->docker-compose)
  Downloading backports.ssl_match_hostname-3.4.0.2.tar.gz
  Running setup.py (path:/home/mdaif/workspace/mozilla/olympia/env2/build/backports.ssl-match-hostname/setup.py) egg_info for package backports.ssl-match-hostname
    
Downloading/unpacking functools32 (from jsonschema>=2.5.1,<3->docker-compose)
  Downloading functools32-3.2.3-2.tar.gz
  Running setup.py (path:/home/mdaif/workspace/mozilla/olympia/env2/build/functools32/setup.py) egg_info for package functools32
    
    warning: no files found matching '*.txt'
    no previously-included directories found matching 'build'
    no previously-included directories found matching 'dist'
    no previously-included directories found matching '.git*'
Installing collected packages: docker-compose, docopt, PyYAML, requests, texttable, websocket-client, docker-py, dockerpty, six, jsonschema, enum34, backports.ssl-match-hostname, functools32
  Running setup.py install for docker-compose
    
    warning: no previously-included files found matching 'README.md'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.un~' found anywhere in distribution
    Installing docker-compose script to /home/mdaif/workspace/mozilla/olympia/env2/bin
  Running setup.py install for docopt
    
  Running setup.py install for PyYAML
    checking if libyaml is compilable
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/check_libyaml.c -o build/temp.linux-x86_64-2.7/check_libyaml.o
    build/temp.linux-x86_64-2.7/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
     #include <yaml.h>
                      ^
    compilation terminated.
    
    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)
    
  Running setup.py install for texttable
    
  Running setup.py install for websocket-client
    changing mode of build/scripts-2.7/wsdump.py from 664 to 775
    
    changing mode of /home/mdaif/workspace/mozilla/olympia/env2/bin/wsdump.py to 775
  Running setup.py install for docker-py
    
  Running setup.py install for dockerpty
    
  Running setup.py install for enum34
    
  Running setup.py install for backports.ssl-match-hostname
    
  Running setup.py install for functools32
    
    warning: no files found matching '*.txt'
    no previously-included directories found matching 'build'
    no previously-included directories found matching 'dist'
    no previously-included directories found matching '.git*'
Successfully installed docker-compose docopt PyYAML requests texttable websocket-client docker-py dockerpty six jsonschema enum34 backports.ssl-match-hostname functools32
Cleaning up...
(env2)$ docker-compose pull 
ERROR: Validation failed in file './docker-compose.yml', reason(s):
Unsupported config option for 'rabbitmq' service: 'name'
```

**Comment by muffinresearch** [comment]
Ok this should be fixed now in ae5aa1f2 - thanks!

**Comment by mdaif** [comment]
You are welcome :)

**Pull request closed without merging**
