### PR TITLE
Fix UnicodeDecodeErrors in the theme update checks service (issue #1090)

### LINKED ISSUE #1090: Many UnicodeDecodeError in Kibana
Seems they are all coming from the theme update checks:
```
Type: <type 'exceptions.UnicodeDecodeError'>, 'utf8' codec can't decode byte 0xe4 in position 43: invalid continuation byte. Data: :./services/utils.py:143#012Traceback (most recent call last):#012 File "./services/theme_update.py", line 219, in application#012 output = update.get_json()#012 File "./services/theme_update.py", line 160, in get_json#012 return json.dumps(data)#012 File "/usr/lib64/python2.7/json/__init__.py", line 243, in dumps#012 return _default_encoder.encode(obj)#012 File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode#012 chunks = self.iterencode(o, _one_shot=True)#012 File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode#012 return _iterencode(o, 0)#012UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 43: invalid continuation byte
```

In kibana (no clue how to link to a specific log line):
- Timestamp: 2015-12-16T09:27:49.000Z
- Uuid: 12ca5d78-3c52-4a0a-a54c-a6596a21b39b
- id_: AVGqHgsWe0LBY8qQvheY

### PR DESCRIPTION
**Pull request by magopian**
Fixes #1090

### CODE REVIEW

**Comment by magopian** [comment]
@jasonthomas I believe this was working previously on phx1 because the connection was set to use utf8 by default on mysql itself? Not sure if you want to do that again, or if we should have this change instead?

**Comment by jasonthomas** [comment]
I've seen these errors in PHX1 before, we are not overriding `character_set_connection` and `character_set_client` in our mysql configuration. This should be a fairly easy change on server side which we can do. Let me know how you want to proceed.

**Comment by magopian** [comment]
Ok, as discussed on IRC, let's do both: merge those changes, and have the changes on the server side (ping @mostlygeek )

**Comment by jasonthomas** [comment]
Changes have been made on dev/stage and prod, unping @mostlygeek

**Comment by magopian** [comment]
@jasonthomas I can still see the errors in kibana, are we sure the workers have been restarted or something? See https://kibana.shared.us-west-2.prod.mozaws.net/#dashboard/temp/AVGrmxBje0LBY8qQt2Sv (this is not urgent :)

**Comment by EnTeQuAk** [comment]
Better safe than sorry, so r+

**Pull request merged**
