### PR TITLE
Change the background to gradient from pin stripe and made footer solid color. (bug 1170302)

### PR DESCRIPTION
**Pull request by FrancescoSTL**
@magopian r?

### CODE REVIEW

**Comment by magopian** [comment]
Is there a bug number for that?

It seems after this change, we're not using the `bg-header.png` file, which could thus be removed (use `git rm` for that):
```
./site-static/img/zamboni/global/bg-header.png
./static/img/zamboni/global/bg-header.png
```

Thanks!

**Comment by FrancescoSTL** [comment]
Yes! The bug number is 1170302. I just removed bg-header.png.

**Comment by FrancescoSTL** [comment]
Here is what the experience now looks like:
screen shot 2015-06-08 at 9 51 50 am

**Comment by magopian** [comment]
The files in `site-static` are actually generated and only used in production (or at least, not locally during the dev as long as you have `DEBUG = True` in the settings).

thanks for the removal of the file, and for the screenshots!

**Comment by FrancescoSTL** [comment]
Is there any way that these two PR's can be pushed at the same time?

**Comment by magopian** [comment]
Sure, i'll merge them both tomorrow, and whenever they'll go live, they should be pushed together.

**Comment by magopian** [comment]
Merged in 9ecb505c69f652f2a15334376ee91c3eb8ca1814

**Pull request closed without merging**
