### PR TITLE
Add/Adjust CSP_REPORT_URI on dev and stage.

### PR DESCRIPTION
**Pull request by jasonthomas**
We changed the endpoint so -dev settings needs to be adjusted. The changes have also been deployed to stage nginx.

r? @muffinresearch 
https://github.com/mozilla/olympia/issues/1289

### CODE REVIEW

**Comment by magopian** [comment]
Do we also need to change it for prod?

r+

**Comment by muffinresearch** [comment]
If this is going to be the same for dev/stage and prod we can just add it to `lib/settings_base.py` and remove all the overrides (apart from local dev which is already overridden to just point at a faked out endpoint on the docker nginx).

**Comment by jasonthomas** [comment]
Yes it's going to be the same on dev/stage and prod.

**Comment by muffinresearch** [comment]
r+

**Pull request merged**
