### PR TITLE
Measure cache invalidation time

### PR DESCRIPTION
**Pull request by kumar303**
Supports https://github.com/mozilla/olympia/issues/1140

### CODE REVIEW

**Comment by tofumatt** [comment]
r+ from me, fwiw

**Comment by mstriemer** [comment]
You've got a `create` and a `save` in both of the test cases. They might not both be required.

I feel like the timing might be timing more than we think potentially. I'm not sure it's guaranteed that the superclasses are the only things that will be called when you call `super(...)`. Perhaps that doesn't matter because we just want to know if this is slow and other stuff happening is cool too. Just worth keeping in mind maybe or maybe not.

r+

**Comment by kumar303** [comment]
> You've got a create and a save in both of the test cases

Oh yeah, duh. I removed the one for the delete case.

As for what this will actually be timing, I think the Django post_save hooks are pretty granular. In any case, it should give us an indication of how slow those hooks are in general. Our theory is that invalidation in post_save is very slow.

**Comment by kumar303** [comment]
What I'm trying to measure is https://github.com/washort/django-cache-machine/blob/4690198122a96a88267323566dc18a5e0437681f/caching/base.py#L43-L47

**Comment by mstriemer** [comment]
:+1:

**Pull request merged**
