### PR TITLE
Require compiled.txt from prod.txt.

### PR DESCRIPTION
**Pull request by kmaglione**

### CODE REVIEW

**Comment by jasonthomas** [comment]
r+

**Comment by magopian** [comment]
what's the use case?

**Comment by magopian** [comment]
I guess it makes more sense like that, indeed

**Comment by kmaglione** [comment]
`simplejson` wasn't installed on dev (which wasn't obvious, since it was listed in requirements), and since we have wheels for all those packages now, we decided there wasn't any reason to keep installing them as RPMs.

**Pull request merged**
