### PR TITLE
Bug 1041873: Add mass deletion tool.

### PR DESCRIPTION
**Pull request by kmaglione**

### CODE REVIEW

**Comment by Lord-of-Darkness** [comment]
Desarrolladores y líderes de Mozilla, que son travestis culo!

Alguien debe colgar ustedes para arriba en sus propias bolas y dejar que su perro muerda su caricatura de una polla!

Posteriormente deben ponerlo tiempo que sea necesario por la garganta hasta que traga a sí mismos en el suicidio!

Ustedes Mozilla está ... Estúpido de mierda coños!
--------------------------------------------------------
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!

**Comment by andymckay** [comment]
There has been no update on this for almost a year. Is this pull request still valid? It has conflicts that need resolving.

**Comment by kmaglione** [comment]
It's still wanted, but it hasn't been a high priority recently. We're almost certainly going to need it or something like it again in the future, though.

**Comment by andymckay** [comment]
Closing for now, it can't be merged cleanly. If its going to be worked on, please re-open.

**Pull request closed without merging**
