### PR TITLE
BUG 1196293 : Remove rating stars from edit review reply.

### PR DESCRIPTION
**Pull request by crdoconnor**
I interpreted https://bugzilla.mozilla.org/show_bug.cgi?id=1196293 as to mean that the ratings should be removed altogether when editing reviews (i.e. remove line 9 from apps/reviews/templates/reviews/edit_review.html).

The test I wrote to verify this fix interacts via HTML ids and classes, so I added some IDs and classes to elements I wanted to interact with.

This pull request also includes a test engine to run the test. This new testing framework 'experiment' is confined to the tests/ directory :)

The engine's advantages:

* It automates virtually every step in https://olympia.readthedocs.org/en/latest/topics/install-olympia/installation.html. just sudo pip install hitch, run hitch init in the tests directory and then run hitch test .
* The test cases you can build with it are relatively clean and readable (IMHO).
* It builds and runs all parts of the system together (MySQL, Memcache, Elastic Search, Rabbit, Django, Celery, SMTP server).
* It downloads and builds specific versions of MySQL/Memcache/Elastic/Rabbit so you can match the exact version to what you have running in production.

The engine's current shortcomings (which will be fixed):

* The set_up is currently very slow as it re-runs pip install, runs migrations, installs fixtures and runs generate_addons at the beginning of every test. This means it is entirely self-bootstrapping but individual test runs are slow (about 2 minutes on 2nd run). I'll implement some caching to deal with this which should bring it down to about 15 seconds (or less).
* There should be a way to get it to run the tests with docker as well.
* Celery is not running yet.
* While it should theoretically work on Mac OS and any Linux distribution, the framework is not yet set up to translate the packages required yet - e.g. libxml2-dev on ubuntu -> libxml2 on brew.
* Probably some bugs I don't yet know about.

### CODE REVIEW

**Comment by crdoconnor** [comment]
Noted. I thought there was something not quite right about this.

Will re-issue later.

**Comment by magopian** [comment]
This looks interesting, but I have two remarks:
1/ I'd rather have the hitch experience in its own separate PR, it's not related to the bug
2/ I don't understand where's the fix for the bug? I can only see the addition of html classes

**Comment by crdoconnor** [comment]
1. Well, it included a test that verified the bug, but I understand if you want it in a separate PR. Maybe I'll do a couple more bug fixes first before submitting tests.

2. I was being dumb and misinterpreted the bug report to mean "remove star ratings from edit page" (line 9 on the edit template). I'll issue the actual fix a bit later on.

**Comment by magopian** [comment]
I understand and saw the test, but would rather have that done in two separate steps. I'm not sure I'm ready to switch the repo to hitchtest (or even use it), even if it looks nice, I'll have to play a bit more with it first, and need to discuss it!
Regarding 2., it's not being dumb, it's just misunderstanding, happens all the time on the internetz, right? :)

**Pull request closed without merging**
