### PR TITLE
Made JWT info copy/pasteable (bug 1215323)

### PR DESCRIPTION
**Pull request by Nolski**

### CODE REVIEW

**Comment by magopian** [comment]
curious why those two are still inputs in a form. Why not keep the form only for the "submit" button, and have simple labels/divs/spans/whatever to display the key and secret?

Other than that, looks good to me
r+wc

**Comment by Nolski** [comment]
Most other API key pages seem to put the keys in an input field and I think this is for two main reasons.

1. The input field can have a fixed width but still be copy/pasteable for easy access to the key.
2. Seeing as the input field is separated from the rest of the UI visually it stands out as more of a call to action.

**Comment by magopian** [comment]
ok i'm sold. SHIP IT :)

r+

**Comment by Nolski** [comment]
:shipit:

**Pull request merged**
