### PR TITLE
Add a new en-GB locale (bug 1190118)

### PR DESCRIPTION
**Pull request by magopian**
Fixes [bug 1190118](https://bugzilla.mozilla.org/show_bug.cgi?id=1190118)

### CODE REVIEW

**Comment by magopian** [comment]
@clouserw I don't think this is enough to add a new locale (I don't see the strings localized, for example the `Add to favorites` string on an add-on listing is unchanged with the `en-GB` locale, while it should read `Add to favourites`).

**Comment by clouserw** [comment]
@magopian it's been a long time since I dug into l10n on AMO.  Were you using an updated .po file and a compiled .mo file?

**Comment by magopian** [comment]
Nope, there's no .mo file, how do I build it?

**Comment by satdav** [comment]
@clouserw  how does he build a .mo file also thats not on pontoon the .mo file

**Comment by clouserw** [comment]
`msgfmt messages.po`
`msgfmt javascript.po -o javascript.mo`

**Comment by magopian** [comment]
Updated the PR with the `.mo` files. @clouserw r?

**Comment by clouserw** [comment]
@magopian sure. r+

**Pull request merged**
