### PR TITLE
Fix the UnicodeDecodeError in addons.cron.unhide_disabled_files (issue #1099)

### LINKED ISSUE #1099: Could not unhide file and UnicodeDecodeError
Investigating the kibana logs, I found out a bunch of UnicodeDecodeError in the `addons.cron.unhide_disabled_files` function:

```
Could not unhide file: /mnt/storage/addons.mozilla.org/guarded-addons/257017/yemark_移动书签-1.2-fx-windows.xpi. :/data/olympia/apps/addons/cron.py:319#012Traceback (most recent call last):#012 File "/data/olympia/apps/addons/cron.py", line 310, in unhide_disabled_files#012 .get(version__addon=addon, filename=filename))#012 File "/data/olympia/venv/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get#012 num = len(clone)#012 File "/data/olympia/venv/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__#012 self._fetch_all()#012 File "/data/olympia/venv/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all#012 self._result_cache = list(self.iterator())#012 File "/data/olympia/venv/src/django-cache-machine/caching/base.py", line 150, in iterator#012 query_string = self.query_key()#012 File "/data/olympia/venv/src/django-cache-machine/caching/base.py", line 141, in query_key#012 return sql % params#012UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 7: ordinal not in range(128)
```

See https://kibana.shared.us-west-2.prod.mozaws.net/#dashboard/temp/AVGr9O6Ve0LBY8qQLwI1

### PR DESCRIPTION
**Pull request by magopian**
Fixes #1099

### CODE REVIEW

**Comment by magopian** [comment]
So, seems the issue is that if you don't provide a unicode string to `os.walk` (see https://github.com/mozilla/olympia/pull/1100/files#diff-49f44d6ae7129208f7593105b1f75568R304), then it'll give you bytes back, which will break on files with non-ascii characters.

**Comment by magopian** [comment]
Didn't mean to close this one.

**Comment by EnTeQuAk** [comment]
It all makes sense but I'd love to see a breaking test to be honest.

**Comment by EnTeQuAk** [comment]
Thanks for the update, if tests pass, r+

**Pull request merged**
