### PR TITLE
unlisted addons submissions and beta files validation are in beta status (bug 1173064)

### PR DESCRIPTION
**Pull request by magopian**
Fixes [bug 1173064](https://bugzilla.mozilla.org/show_bug.cgi?id=1173064)

Listed add-on submission
screen shot 2015-06-10 at 11 54 33

Unlisted add-on submission
screen shot 2015-06-10 at 11 54 19

Upload a new file or add a new version to an unlisted add-on
screen shot 2015-06-10 at 12 01 47

Upload a beta version on a fully reviewed listed add-on, validation failed
screen shot 2015-06-10 at 16 12 21

Upload a beta version on a fully reviewed listed add-on, validation failed, not publishing to beta channel
screen shot 2015-06-10 at 16 12 33

### CODE REVIEW

**Comment by magopian** [comment]
@kmaglione r? Is that what you had in mind?

**Comment by kmaglione** [comment]
Yep, this looks perfect. It looks like I forgot one thing when I filed the bug:

We should add "(beta)" to the "Unlisted" checkbox on the devhub add-on versions page, and the same warning to the pop-up confirmation box as to the initial submission dialog.

Sorry I didn't think of that earlier.

**Comment by magopian** [comment]
No problem, here are the new modifications:

screen shot 2015-06-11 at 10 39 28
(can you please validate the wording on that one?)

screen shot 2015-06-11 at 10 38 59

**Comment by kmaglione** [comment]
The wording looks good. I'm slightly worried that "Unlisted (beta)" suggests that the add-on, rather than the feature, is beta. though. I think "(beta)" should go at the end of the description, but otherwise it looks good.

r+wc

**Pull request merged**
