### PR TITLE
Bug 1198855 - Linking directly to Version Information or Development Channel sections should be possible

### PR DESCRIPTION
**Pull request by palant**
The change to the expando logic affects all pages, not just the add-on details page. However, the new behavior is the correct one IMHO.

### CODE REVIEW

**Comment by magopian** [comment]
Looks good to me, three minor nits ;)

Thanks!

**Comment by palant** [comment]
Fixed the nits.

**Comment by magopian** [comment]
Wow that was fast, thanks!

**Comment by magopian** [comment]
Fixed by c9659a3e3b8e40d60bfb8da6de5c58c5b4787dda

**Pull request closed without merging**
