### PR TITLE
Use reject_reasons dict consistenly (bug 1140346)

### PR DESCRIPTION
**Pull request by magopian**
Fixes [bug 1140346](https://bugzilla.mozilla.org/show_bug.cgi?id=1140346)

### CODE REVIEW

**Comment by magopian** [comment]
@kmaglione @clouserw r? I'd like that in for the code freeze today if possible.

**Comment by diox** [comment]
No test ?

**Comment by magopian** [comment]
well, of course there's a test, what do you mean :angel:

**Comment by diox** [comment]
r+

**Pull request merged**
