### PR TITLE
s/<b>/<strong>/ due to a11y issues (bug 1196955)

### PR DESCRIPTION
**Pull request by Nolski**

### CODE REVIEW

**Comment by magopian** [comment]
Good start!

I think you need to update your searches to only match on the first part of the opening tag (to allow for attributes) in the html files: `<b` instead of `<b>`.
You also need to take the `b,` into account for the css files. Maybe searching for `\bb\b` globally would do the trick? (`\b` matches word boundaries, so `\bb\b` matches `b` only if it's a word).

**Comment by magopian** [comment]
You also need to update the few failing tests that are using selectors with `b` instead of `strong`

**Comment by magopian** [comment]
Still a few failing tests

**Comment by Nolski** [comment]
Looking through this PR and the amount of styling changes that happen in the javascript, I'm worried that this may be a bit too risky to merge in, even if I update the python unit tests to no longer fail.

Perhaps we should close this and mark it on a TODO for any new front end components?

**Comment by magopian** [comment]
I think you're right. I'd vote for taking care of all future code (not sure about a TODO, where would that go?). Maybe we simply need to communicate about that somewhere (in the docs? on the mailing list? in some coding standards?) and make sure to double check that in code reviews.

**Pull request closed without merging**
