### PR TITLE
Revert "First pass at a style refresh"

### LINKED ISSUE #1195: Back out new theme until it's opt-in or flagged per-user in some way.
So the theme changes don't get in the way of stabilisation efforts can we either revert it or have it so it gets added only with the presence of a cookie or something?

This is dev currently:

add-ons_for_firefox

### PR DESCRIPTION
**Pull request by muffinresearch**
Reverts mozilla/olympia#1078 (This patch came from clicking the github revert button on the PR).

Temporary fix so we don't conflate fixing jqery-migrate removal with style regressions. 

When this gets added back it needs to be easy to turn on and off.

Fixes #1195

### CODE REVIEW

**Comment by tofumatt** [comment]
Oh, darn, I said in #1078 we should have a waffle flag or something for this: https://github.com/mozilla/olympia/pull/1078#issuecomment-169027349

Sorry, I should've been more diligent.

**Comment by muffinresearch** [comment]
> Oh, darn, I said in #1078 we should have a waffle flag or something for this: #1078 (comment)

> Sorry, I should've been more diligent.

Np - I think it might work better if the built js + css files are added as extra requests in the page (whilst this is being built out). Given that it's mostly a layer on top of existing styles etc - that might help make it more easy to turn off and on as needed. Also it would be great if it can be flagged / cookied on a per-user basis.

**Comment by magopian** [comment]
Anything particular I should look for in this one? It's only using a plain git revert, right?

If so, r+

**Comment by muffinresearch** [comment]
> Anything particular I should look for in this one? It's only using a plain git revert, right?

Yep via the revert button.

**Pull request merged**
