### PR TITLE
Added visibility to addon-status (bug 1157349)

### PR DESCRIPTION
**Pull request by robhudson**

### CODE REVIEW

**Comment by robhudson** [comment]
Small status box:
screenshot 2015-04-28 17 03 25

My submissions list:
screenshot 2015-04-28 17 03 37

**Comment by magopian** [comment]
Do we also want this information on the dashboard?

**Comment by magopian** [comment]
r+wc

**Comment by magopian** [comment]
Oh, I think we also want that on the review page of the add-ons in the editor tools (eg `http://localhost:8000/en-US/editors/review/tabsmacki`).

I believe it should go somewhere in here:
screen shot 2015-04-29 at 15 05 31

**Comment by robhudson** [comment]
Can you share where the dashboard is? I'll add something to the editor tools.

**Comment by magopian** [comment]
Sure! The dashboard is the "home page" of the devhub (the link to the developer hub in the top-most menu): `/en-US/developers/`

**Comment by magopian** [comment]
r+

**Pull request merged**
