### PR TITLE
Get .srcElement from originalEvent in syntaxhighlither/shCore.js

### LINKED ISSUE #1273: get .srcElement from originalEvent in syntaxhighlighter/shCore.js
Because of https://jquery.com/upgrade-guide/1.9/#removed-properties-of-the-event-object

Related to #1197

### PR DESCRIPTION
**Pull request by magopian**
Fixes #1273

### CODE REVIEW

**Comment by muffinresearch** [comment]
Commit msg has a typo.

r+wc

**Comment by magopian** [comment]
Fixed the typo (I think?)

**Comment by muffinresearch** [comment]
Actually again is this related to jquery or just IE propreitary stuff?

**Comment by magopian** [comment]
wontfix, not related to jquery after all

**Pull request closed without merging**
