### PR TITLE
Added action string for comments to log view

### PR DESCRIPTION
**Pull request by wagnerand**

### CODE REVIEW

**Comment by magopian** [comment]
What is that used for? Can you add a test for it?

**Comment by wagnerand** [comment]
I don't think a test is needed for this.

It fixes a missing string on the log view page. You can see in the attached screenshot, that the review action for one add-on is missing.
screenshot

**Comment by magopian** [comment]
I understand ;)

Regarding the test: could you please duplicate one of those and add it after [here](https://github.com/mozilla/olympia/blob/master/apps/editors/tests/test_views.py#L316)?

**Comment by wagnerand** [comment]
Sorry, I didn't know there are tests for this. I included one.

**Comment by magopian** [comment]
Excellent, thanks!
I'll merge when the build succeeds (which will be when I figure out why it just fails since today...)

**Comment by magopian** [comment]
Thanks @wagnerand !

**Pull request merged**
