### PR TITLE
Highlight code with actual syntax in the diff viewer

### PR DESCRIPTION
**Pull request by kmaglione**
This is on top of #642, since it would conflict with those changes, but is a separate PR since it's not very closely related, and is somewhat lower priority.

### CODE REVIEW

**Comment by kmaglione** [comment]
r? @wagnerand 

Just the final commit.

**Comment by wagnerand** [comment]
Looks good to me, thank you!

r+ on the final commit

**Comment by kmaglione** [comment]
Thanks. Will merge after the base PRs are approved.

**Comment by kmaglione** [comment]
a2cbc650c6a0c93e

**Comment by magopian** [comment]
Not sure if you were waiting for a review from me? If so, r+

**Comment by kmaglione** [comment]
Thanks. Need to merge #642 first.

**Pull request merged**
