### PR TITLE
Remove commonplace deps

### PR DESCRIPTION
**Pull request by muffinresearch**
Looks like commonplace was leftover from the split from Zamboni.

### CODE REVIEW

**Comment by tofumatt** [comment]
Cool, I'll check this version out and try it later to see if it works on docker any better (I should be able to use this without replacing any Docker code, right?)

**Comment by muffinresearch** [comment]
Yes I think so because the npm install is runtime (not build time) iirc.

**Comment by tofumatt** [comment]
Awesome. Will try it out and report back today :)

- tofumatt

On 28 September 2015 at 15:17:53, Stuart Colville (notifications@github.com) wrote:

Yes I think so because the npm install is runtime (not build time) iirc.

**Comment by magopian** [comment]
I'm pretty sure those aren't used on olympia.

**Comment by tofumatt** [comment]
Thus far this doesn't solve my issues (https://bugzilla.mozilla.org/show_bug.cgi?id=1208854), but they are likely unrelated.

**Comment by tofumatt** [comment]
Oops, sorry, forgot to comment. I tried this out and it worked fine. r+

**Pull request merged**
