### PR TITLE
Bug 1038301 continue to download btn

### PR DESCRIPTION
**Pull request by FrancescoSTL**
Removed e.preventDefault() which was preventing outbound button clicks on collections pages.

r? @kmaglione

### CODE REVIEW

**Comment by kmaglione** [comment]
Hm. I'm not sure what the implications of this will be. In any case, if removing this is the correct solution, it means removing the entire file, since this essentially nullifies its entire purpose.

The idea of this file is that it it only remains in effect until the install button code has loaded, and then removes the listeners and re-triggers any click events it blocked in the mean time. If that's not happening, and this is what's breaking the buttons, we need to figure out why.

**Comment by FrancescoSTL** [comment]
@kmaglione This is the change that we were discussing previously. I moved the .unbind and .undelegate outside of the callback function in $window.bind('buttons_loaded'). Both still exist within the callback function in the original .delegate().

**Comment by FrancescoSTL** [comment]
Reverted the preloaded.js file to its original format and removed a copy of jQuery from being loaded in settings_base.py. This seems to be what was causing the issue in the first place.

**Comment by kmaglione** [comment]
@magopian Do you have any thoughts on this? I'm not 100% sure this won't prevent jQuery from being loaded into some pages.

**Comment by magopian** [comment]
Removing the jquery from the `common` bundle seems risky (I could imagine the `common` bundle used in many places without anything else, at least without one of the "other" jquery).

Would it work to remove the jquery from `preload` (https://github.com/mozilla/olympia/pull/597/files#diff-077ac9806d2efe66b21b5db93d2a96b0L664) instead?

It seems that `preload.js` is only used in two files:
- `templates/base.html`: it also has the `common` bundle, so it should be ok
- `templates/impala/base.html`: it's not using the `common` bundle, or any other bundle that includes jquery, but maybe jquery could be added to the `impala` bundle (which is included in this template)

Adding jquery to the `impala` bundle would probably cause some pages to load jquery twice (where it wasn't before), which may simply move the problem elsewhere.

Another solution would be to pull jquery out of all the bundles, and add it manually to the base templates (that I mentioned above). This would solve the "multiple jquery" issues altogether, but would also mean having mone more js file to download per page/per user.

Any thoughts @diox (or an idea on who I should be pinging for that?)

**Comment by FrancescoSTL** [comment]
@magopian When I remove the jquery from preload it works. Additionally, because the button in question isn't loading any jQuery (it is an href), I'm thinking that the preloaded.js file doesn't apply to it. If we specifically exclude this button from the preload logic, it will work again. To replicate, add a:not('concealed') to the main .delegate: http://pastebin.com/Yp1qPLkd

The original can be seen here: https://github.com/mozilla/olympia/blob/master/static/js/impala/preloaded.js#L16

**Comment by magopian** [comment]
How about that: add a class (like `no-preload`) to the button that you don't want the preloading on, and then filter that out in the `preload.js` file?

**Comment by kmaglione** [comment]
I suspect that removing jQuery from preload fixes the problem because it causes preloaded.js to throw an error rather than add the listeners. That script definitely requires jQuery to be loaded first. And if another copy of jQuery were somehow being loaded from elsewhere first, we'd still have the same problem.

I don't think adding a `no-preload` class is going to work. The code in `preloaded.js` is clearly broken on any page which loads a second copy of jQuery, so we'd have to add that class to every button, which is the same as just removing the file.

Maybe we can track down the places where common is being loaded without preload, and either add it, merge preload into common, or make a separate preload group that only includes jQuery?

**Comment by FrancescoSTL** [comment]
The "add to firefox" buttons seem to be unaffected by this issue. Theoretically, if we were to implement the 'no-preload' class fix, it would only need to be added to buttons other than "add to firefox" (continue to download, and the "download firefox" CTA that is blocked by this bug).

I agree, however, that it would be best to fix the issues with preloaded.js, for anything else could cause more issues in the future.

**Comment by kmaglione** [comment]
They seem unaffected only because they have their own click handlers which happen to work despite the interference from `preloaded.js`. But either way, `preloaded.js` is completely broken for this page, so if we're going to resort to a kludgy solution, the kludgy solution I'd lean toward is removing that script entirely.

But I'd *much* prefer to fix the root problem of loading extra copies of jQuery. For a lot of reasons. So thanks for continuing to look into this :)

**Comment by magopian** [comment]
FYI, PR #625 changes the "tabzilla" to use the new, static version: https://github.com/mozilla/tabzilla/

They say in there that this one doesn't inject jquery in the page. Could that explain (and thus fix?) some of the issues with multiple jquery on the page?

**Comment by magopian** [comment]
After going through it again, I think the idea in this PR is the correct one: the `preload` bundle is added to the only template that also has `common` (`templates/base.html`), and is added before it. So removing jquery from `common` makes the more sense.

I've also double checked that the `preload` bundle is never loaded on the same page as one of the other bundles that include jquery (`zamboni/discovery` and `zamboni/mobile`).

Closing this PR in favor of #826 (for the rebase).

**Pull request closed without merging**
