### PR TITLE
Get most recent FileUpload status instead of a 500 (bug 1221705)

### PR DESCRIPTION
**Pull request by mstriemer**
https://bugzilla.mozilla.org/show_bug.cgi?id=1221705

### CODE REVIEW

**Comment by kumar303** [comment]
r+wc, I think this is ok for now but it won't handle concurrent signing very well.

A better approach would be to make a change so the flow is more like this:

* `PUT /addons/@thing/versions/0.0.1/` to create a new version
* poll `GET /addons/@thing/versions/0.0.1/upload/e90a35d583704a15b71e197e3b7d165f/` to check its status

Here is a concurrency scenario I can think of (but there might be others). A developer adds a `jpm sign` hook to their pull request hook. They make a pull request for an add-on that should be signed but it has a typo that will cause a validation failure. They notice it immediately after pushing the code, fix the problem, and push a new change. Due to high load in their pull request hook handler, the fixed code triggers `jpm sign` before the broken code. There is a chance that the wrong add-on uploaded with `jpm sign` might win when `sign` queries for last-created-upload.

**Comment by mstriemer** [comment]
Yeah, it is supposed to only accept one upload at a time but that isn't implemented. I think that's why I used `get()` here originally but didn't leave a comment for myself. My original idea was that it should give you `423 LOCKED` if there is currently a `FileUpload` that isn't processed. I'll add support for that.

**Comment by kumar303** [comment]
ok, I suppose a 423 Locked response would address the concurrency problem. It seems like it should be possible to sign different versions in parallel though. In the rapid fire pull request scenario I mentioned the second one would trigger a 423 and just fail which isn't too nice.

**Comment by mstriemer** [comment]
I'd imagine `jpm sign` is something you'd run on a tag and hopefully if they have that setup in their CI they're also running the validator tests against their code so the build will have broken anyway.

The situation where there are two uploads being validated at the same time and they both pass sounds confusing to me and would result in a race between the validations of the two uploads. So that's why I decided on the locked response.

**Comment by mstriemer** [comment]
The `423 LOCKED` response is pretty much done but needs some more test coverage. I'll merge this now and get that in later today in another PR.

**Pull request merged**
