### PR TITLE
robots by default in docker

### PR DESCRIPTION
**Pull request by andymckay**

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
I like that Idea, r+

**Comment by muffinresearch** [comment]
Thicky question but I'm curious about the use-case. Why do we need robots on for docker by default? I would expect only prod to need it on - but maybe I'm missing something.

**Comment by EnTeQuAk** [comment]
If I understood that correctly we're deploying on dev via docker but correct me if I'm wrong, this way we can test robots easier on dev. At least that was what Iw as thinking.

**Comment by muffinresearch** [comment]
@EnTeQuAk but settings make it off in -dev and stage [1]. I don't think we're deploying with docker yet anywhere.

[1] https://github.com/mozilla/olympia/pull/892/files#diff-077ac9806d2efe66b21b5db93d2a96b0R1153

**Comment by muffinresearch** [comment]
The other thing is if we have robots on by default and any 3rd parties or devs stand-up olympia on the web and it gets crawled, they won't have all the content but we might get duplicate content on any pages that aren't provided by data. Not sure if that's an issue. At least if robots is off by default, turning it on would be a conscious decision in those cases.

**Comment by andymckay** [comment]
I came along to write some code for robots.txt and was surprised to find it off by default, it made sense to me to have the most functionality on by default. I'm not quite sure I see the robots.txt on other sites being a problem, its all on different domains and won't have the same content right?

**Comment by muffinresearch** [comment]
> I came along to write some code for robots.txt and was surprised to find it off by default, it made sense to me to have the most functionality on by default. I'm not quite sure I see the robots.txt on other sites being a problem, its all on different domains and won't have the same content right?

I don't know the extent of content that would be the same - but here's the doc on duplicate content for future reference https://support.google.com/webmasters/answer/66359?hl=en.

**Pull request merged**
